### ISSUE TITLE
Need clarification on interpretation of autograder results

### ISSUE THREAD

**Issue by tuesmiddt** [source-academy/grader#12]
Currently, autograder returns: 
```
[
  {'marks': 1, 'resultType': 'pass'},
  {'marks': 4, 'resultType': 'pass'}
]
```
Questions:
1. Does `resultType: pass` mean all test cases passed or autograder result is valid? By extension, does `resultType: "error"` mean that 0 marks should be awarded?
2. Since awarded and maximum grade can be any arbitrary number depending on how many test cases avengers write, backend needs to know how to scale the grade awarded. If tests (`{'marks': 1, 'resultType': 'pass'}`) are of equal weightage, we need something like `{marks: 1, maxMarks: 10, resultType: "pass"}`. If not, autograder can return something like: 
```
{
  marks: 5,
  maxMarks: 20,
  testResults: 
    [
      "pass",
      "pass",
      "Error1, Error2, Error3" // output from current parseError function
      "pass",
    ]
}
```

**Comment by ningyuansg** [comment]
1. A `pass` indicates that no syntax or runtime errors are raised for that grader program. It is independent of the marks. By extension, yes, `resultType === 'error'` should translate to `marks = 0` for that grader program.
2. I get what you mean with this one.
    - The grader cannot currently infer the maximum marks from the JSON that backend sends.
    - I think the best solution to this is to specify that the maximum marks for a grader program as a required field in the JSON  that backend sends. There would then be some changes to the grader API.
    - Good news is no change from the XML specs since `maxGrade` is already an attribute of each `PROBLEM`.
    - Which means I will also rename 'marks' to 'grade' in the grader API to keep things consistent.

---

A proposal for the new grader API. First, the JSON that backend sends to the grader. This includes new changes made in the XML specs since the grader was first written:

```typescript
{
    graderPrograms: string[]
    studentProgram: string
    maxGrade: number
    interpreter: {
        chapter: number
        name: string | null
        externals: string[]
        globals: Array<{
            identifier: string
            value: string
        }>
    }
}
```

(`globals` is an array of objects with two keys `identifier` and `value` which both have values of type `string`)

Next, the JSON response from grader to backend:

```typescript
{
    grade: number
    maxGrade: number
    results: Result[]
}

Result = {
    type: "pass" | "error"
    error?: {
        description: string
        line: number
        location: "grader" | "student"
    }
}
```

Is this ok?

**Comment by tuesmiddt** [comment]
I'm not quite sure why backend sends `maxGrade`. The way I understand it is: 
- Each question has a `maxGrade`
- Autograder `maxGrade` is unrelated to question `maxGrade`. If there are 20 autograder tests, autograder `maxGrade` could be 20 while question `maxGrade` is only 5, in which case the actual grade will be `autograderGrade / autograderMaxGrade * questionMaxGrade`
Am I missing something?

For the JSON that backend sends to the interpreter, can we follow the current library schema like so:
```
{
    graderPrograms: string[]
    studentProgram: string
    maxGrade: number
    library: {
        chapter: number
        external: {
          name: string | null
          symbols: string[]
        }
        globals: Array<{
            identifier: string
            value: string
        }>
    }
}
```

No issues with the general response schema. At the moment, we're not doing anything with the results so I'll probably just store it as is.

**Comment by ningyuansg** [comment]
I recall a meeting where we discussed the possibility that the backend would store only a percentage grade for each assessment. That is, each assessment's final stored grade in the database is in the range `[0, 1]`. The module administration will then be able to apply their preferred weightage multipliers to this percentage grade to calculate a student's final grade.

For example, if there are only two assessments, _Mission X_ and _Mission Y_, the backend might at the end of the semester have this recorded for a particular student:

```json
{
    "Misssion X": 0.75,
    "Mission Y": 0.25
}
```

Which indicates that the student had obtained 75% of the possible maximum numberic grade within _Mission X_, but only 25% for _Mission Y_.

The module administration can do whatever they like to this information to determine the final module grade. For example, if they decide that _Mission X_ should be worth twice _Mission Y_, then the total grade for the student would be:

```typescript
( (2 * 0.75) + (1 * 0.25) ) / 3
```

This system would imply that the numeric maximum grade within each assessment does not matter, since at the end we only care about a percentage.

Therefore, module staff _should_ set a numeric maximum grade for an assessment at any arbitrary number, e.g. 1000, and then determine the weightage of each problem by assigning an appropriate maximum grade for that problem relative to its weight, e.g. 500 for a problem worth 50% of an assessment.

Following this, module staff _should_ write their grader programs such that they add up to their problem's maximum grade.

In the above case, we would then only need to know the maximum grade of each problem. Maximum grade of the assessment is inferred from their sum, and we specify that maximum grade of grader programs must equal maximum grade of the problem.

CC: prof @martin-henz

**Comment by tuesmiddt** [comment]
Each question score will be stored in the backend in a format equivalent to `numerator: x, denominator: y` to avoid rounding disputes. Assessment percentage will not be stored but instead be computed from its questions. I thought `maxGrade` was a reflection of the question's weightage within the assessment, not the `denominator`. 

Based on your response, I think backend doesn't need to send `maxGrade` to the autograder. I will take response `grade` as `numerator` and `maxGrade` parsed from XML as `denominator`.

The rules you mentioned concerning setting of maximum grades for questions within an assessment will have to be followed strictly by teaching staff. I will add a `warning` log event if `grade > maxGrade`. Autograder response will be stored even if that happens as `maxGrade` can be manually edited at a later date. Back-end will not be able to validate whether `maxGrade` is actually achievable based on the provided grading programs.

**Comment by ningyuansg** [comment]
In that case, the grader will expect the following JSON from backend:

```typescript
{
    graderPrograms: string[]
    studentProgram: string
    library: {
        chapter: number
        external: {
          name: string | null
          symbols: string[]
        }
        globals: Array<string[]>
    }
}
```

`globals` being the array of a two-element array `[identifer, value]`.

And there will be a minor change renaming 'marks' to 'grade' in the JSON response from grader to backend:

```typescript
Array<{
    grade: number
    resultType: 'pass' | 'error'
}>
```

If there are no problems, I'll get this implemented by tomorrow (Monday). 

W.r.t. the rules about setting the weightage of each problem based on the ratio of the problem's numeric max grade and the assessment's numeric max grade, and the requirement for the sum of maximum grader program return values (grades) to be equal the numeric max grade of the problem: I'll include that in the avenger handbook, and relay this to the mentors during the upcoming meeting.

**Comment by ningyuansg** [comment]
Right, sorry. Got the JSON response a bit wrong.

```typescript
type Response = Array<PassResult | ErrorResult>

type PassResult = {
    grade: number
    resultType: 'pass'
}

type ErroResult = {
    errors: Error[]
    resultType: 'error'
}

type Error = {
    errorType: 'runtime' | 'syntax'
    line: number
    location: 'grader' | 'student'
}
```

Example:

```json
[
    {
        "grade": 30,
        "resultType": "pass"
    },
    {
        "grade": 50,
        "resultType": "pass"
    },
    {
        "errors": [
            {
                "errorType": "syntax",
                "line": 28,
                "location": "student"
            },
            {
                "errorType": "syntax",
                "line": 32,
                "location": "student"
            }
        ],
        "resultType": "error"
    }
]
```

(Minor change in value of key `errorType`: use lowercase spellings).

**Comment by tuesmiddt** [comment]
alright that works

**Comment by ningyuansg** [comment]
Also, type for `name` of `external` in `library` cannot be `null`. It's can be 'NONE', 'TWO_DIM_RUNES', 'THREE_DIM_RUNES', 'CURVES', or 'SOUND'. This is because in the XML specs, `name` is an attribute of the element `EXTERNAL`, and it is specified that all attributes must be present for an element.

(Sorry if the `null` was there because of specs we had wrongly defined)

**Comment by tuesmiddt** [comment]
Yep that's fine. Name is currently a required field that defaults to "none". Can you take this string in lowercase?

**Comment by ningyuansg** [comment]
Would prefer uppercase since frontend already implemented it in uppercase
